table Financials
	lineageTag: 5efb8b3a-896c-4a20-a29d-ac349ab845a5

	measure 'Total Sales' = SUM(Financials[Sales])
		lineageTag: 329f9525-b006-4714-86c5-d4172befef73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Segment
		dataType: string
		lineageTag: 0fbfc8c7-7a51-4be0-8e8a-53776a7f051d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 385af24b-2118-405e-af74-e6ab047bdadf
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 584ed0fc-8fce-4e74-9407-bb592e407f24
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 4deed399-8a6a-4793-a2f7-4d95c6c999e3
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 41d5c872-3c89-414d-ad15-85a0b345083f
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: f231043a-b61c-40ba-b079-90b409557a75
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 0a2f2281-e66d-4747-8693-4234dbbe4b5c
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: int64
		formatString: 0
		lineageTag: 35e56fa9-bec4-4446-b7d4-015795ebceff
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

	column Discounts
		dataType: double
		lineageTag: 6d10c3c6-201c-452b-b32e-bf8b7e22b554
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 9eaa8077-1263-4985-9686-4d8217263f0e
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: int64
		formatString: 0
		lineageTag: 753d72be-a65b-4292-a868-40fcaab8acfe
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: b58283e8-3947-4bfc-8cd9-487f03d234b6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 348124df-a84d-4e98-935d-066802d124f0
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: c40a3adf-bafb-4b72-b936-10d5ab7764b1
			defaultHierarchy: LocalDateTable_31a9119e-4799-4e71-a466-362b8aaddf70.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 9a276eb9-2c9b-4c97-a5c9-6eede69cb32f
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 9f18ec40-ce60-4ca5-a834-3709b6bd503e
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 562e708f-f067-47ed-8303-eecc1a1f2df1
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Financials = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MyProject\data\Financials.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", Int64.Type}, {"Discounts", type number}, {"Sales", type number}, {"COGS", Int64.Type}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

